sonar.projectKey=user-service
sonar.projectName=user-service
sonar.sources=services/user-service/src
sonar.exclusions=**/node_modules/**,**/*.test.js,**/coverage/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=**/*
sonar.javascript.node.maxFileSize=1000